* workaround for known /run-mount bug * optimized appuser-uid fixing

diff --git a/assets/init b/assets/init
--- a/assets/init
+++ b/assets/init
@@ -1,35 +1,14 @@
 #!/bin/bash
+set -e
 
-DOCKERHOST=$(ip route show | grep -e ^default | awk -F" " '{ print $3 }')
-
-##
-## setup defaults
-##
-SETUP_DIR="/docker/setup"
-
+BUILD_DIR="/docker/build"
 LOG_DIR="/var/log"
 
-_setupRuntime() {
-    # set up what has to be set up
-    for i in `ls -A ${SETUP_DIR}`; do
-        if [ "$i" == ".keepme" ];then continue;fi
-        echo "Setting up $i..."
-        source "${SETUP_DIR}/$i"
-    done
-}
+for i in `ls -A ${BUILD_DIR}`; do
+    echo "Building $i..."
+    source "${BUILD_DIR}/$i"
+done
 
-echo "Setting up runtime environment..."
-_setupRuntime
-
-case "$1" in
-    run)
-        echo "Starting npm ..."
-        exec su ${APP_USER} -c "cd ${APP_HOME};npm start"
-        ;;
-    *)
-        echo "Executing custom command ..."
-        exec su ${APP_USER} -c "cd ${APP_HOME};$@"
-        ;;
-esac
-
-exit 0
+# cleanup
+rm -rf /var/lib/apt/lists/*
+rm -rf /var/cache/apt/archives/*
